version: "3.5"
services:

  cve_search:
    image: w1tch/cve_search
    hostname: cve_search
    depends_on:
      - redis
      - mongo
    restart: always
    environment:
      - PYTHONUNBUFFERED=TRUE
      - WORKER_SIZE=1
    ports:
      - 443:5000
    networks:
      - frontend
      - backend

  redis:
    image: w1tch/cve_search-redis
    hostname: redis
    restart: always
    volumes:
      - "./.cve_search_data/cve_search_redis:/data"
    expose:
      - 6379
    networks:
      - backend

  mongo:
    image: w1tch/cve_search-mongo
    hostname: mongo
    restart: always
    volumes:
      - "./.cve_search_data/cve_search_mongodb:/data/db"
    expose:
      - 27017
    networks:
      - backend

networks:
  frontend:
  backend:
